// Same 20 language codes as the application's language selector.
// title, download, share, close, saving help, share error
export const EXPORT_PREVIEW_TEXT: Record<string, readonly [string, string, string, string, string, string]> = {
  ko: ["파일 미리보기", "다운로드", "공유 · 파일에 저장", "닫기", "자동 다운로드가 뜨지 않으면 다운로드를 눌러 주세요. 아이폰은 공유에서 ‘파일에 저장’을 선택할 수 있습니다. 저장 확인 창이 뜨면 확인해 주세요.", "공유를 열지 못했습니다. 다운로드를 누르거나 Safari·Chrome에서 다시 시도해 주세요."],
  en: ["File preview", "Download", "Share / Save to Files", "Close", "If the automatic download does not appear, tap Download. On iPhone, choose Save to Files from Share. Confirm any save prompt.", "Could not open sharing. Tap Download or try again in Safari or Chrome."],
  zh: ["文件预览", "下载", "分享 / 存储到文件", "关闭", "如果未出现自动下载，请点击下载。iPhone可通过分享选择存储到文件。如出现保存提示，请确认。", "无法打开分享。请点击下载，或在Safari或Chrome中重试。"],
  vi: ["Xem trước tệp", "Tải xuống", "Chia sẻ / Lưu vào Tệp", "Đóng", "Nếu không tự tải xuống, hãy nhấn Tải xuống. Trên iPhone, chọn Lưu vào Tệp trong Chia sẻ. Xác nhận khi có yêu cầu lưu.", "Không thể mở chia sẻ. Hãy nhấn Tải xuống hoặc thử lại bằng Safari hay Chrome."],
  ru: ["Предпросмотр файла", "Скачать", "Поделиться / Сохранить в Файлы", "Закрыть", "Если загрузка не началась, нажмите «Скачать». На iPhone выберите «Сохранить в Файлы» через «Поделиться». Подтвердите запрос сохранения.", "Не удалось открыть меню «Поделиться». Нажмите «Скачать» или повторите в Safari или Chrome."],
  th: ["ตัวอย่างไฟล์", "ดาวน์โหลด", "แชร์ / บันทึกไปยังไฟล์", "ปิด", "หากไม่ดาวน์โหลดอัตโนมัติ ให้แตะดาวน์โหลด บน iPhone ให้เลือกบันทึกไปยังไฟล์จากเมนูแชร์ และยืนยันเมื่อมีคำขอให้บันทึก", "เปิดการแชร์ไม่ได้ โปรดแตะดาวน์โหลดหรือลองอีกครั้งใน Safari หรือ Chrome"],
  uz: ["Faylni ko‘rish", "Yuklab olish", "Ulashish / Fayllarga saqlash", "Yopish", "Avtomatik yuklanmasa, Yuklab olishni bosing. iPhone’da Ulashish orqali Fayllarga saqlashni tanlang. Saqlash so‘rovini tasdiqlang.", "Ulashish ochilmadi. Yuklab olishni bosing yoki Safari yoki Chrome’da qayta urinib ko‘ring."],
  ph: ["Preview ng file", "I-download", "Ibahagi / I-save sa Files", "Isara", "Kung walang awtomatikong download, pindutin ang I-download. Sa iPhone, piliin ang Save to Files sa Share. Kumpirmahin ang pag-save kapag hiniling.", "Hindi mabuksan ang pagbabahagi. Pindutin ang I-download o subukan sa Safari o Chrome."],
  km: ["មើលឯកសារជាមុន", "ទាញយក", "ចែករំលែក / រក្សាទុកក្នុង Files", "បិទ", "បើការទាញយកស្វ័យប្រវត្តិមិនបង្ហាញ សូមចុចទាញយក។ នៅលើ iPhone សូមជ្រើស Save to Files ពី Share។ សូមបញ្ជាក់នៅពេលមានសំណើរក្សាទុក។", "មិនអាចបើកការចែករំលែកបានទេ។ សូមចុចទាញយក ឬសាកល្បងក្នុង Safari ឬ Chrome។"],
  id: ["Pratinjau berkas", "Unduh", "Bagikan / Simpan ke File", "Tutup", "Jika unduhan otomatis tidak muncul, ketuk Unduh. Di iPhone, pilih Simpan ke File dari Bagikan. Konfirmasikan permintaan penyimpanan.", "Tidak dapat membuka berbagi. Ketuk Unduh atau coba di Safari atau Chrome."],
  mn: ["Файлыг урьдчилан харах", "Татах", "Хуваалцах / Файлд хадгалах", "Хаах", "Автоматаар татахгүй бол Татах товчийг дарна уу. iPhone дээр Хуваалцах цэснээс Файлд хадгалахыг сонгоно уу. Хадгалах хүсэлтийг батална уу.", "Хуваалцах цэс нээгдсэнгүй. Татах товчийг дарах эсвэл Safari, Chrome дээр дахин оролдоно уу."],
  my: ["ဖိုင်အစမ်းကြည့်ရန်", "ဒေါင်းလုဒ်", "မျှဝေ / Files တွင်သိမ်းရန်", "ပိတ်ရန်", "အလိုအလျောက်ဒေါင်းလုဒ် မပေါ်ပါက ဒေါင်းလုဒ်ကိုနှိပ်ပါ။ iPhone တွင် Share မှ Save to Files ကိုရွေးပါ။ သိမ်းဆည်းရန်တောင်းဆိုပါက အတည်ပြုပါ။", "မျှဝေရန်မဖွင့်နိုင်ပါ။ ဒေါင်းလုဒ်ကိုနှိပ်ပါ သို့မဟုတ် Safari၊ Chrome တွင်ထပ်စမ်းပါ။"],
  ne: ["फाइल पूर्वावलोकन", "डाउनलोड", "साझा / Files मा सुरक्षित", "बन्द", "स्वचालित डाउनलोड नदेखिए डाउनलोड थिच्नुहोस्। iPhone मा Share बाट Save to Files छान्नुहोस्। सुरक्षित गर्ने अनुरोध पुष्टि गर्नुहोस्।", "साझा गर्ने सुविधा खोल्न सकिएन। डाउनलोड थिच्नुहोस् वा Safari वा Chrome मा फेरि प्रयास गर्नुहोस्।"],
  bn: ["ফাইল প্রিভিউ", "ডাউনলোড", "শেয়ার / Files-এ সংরক্ষণ", "বন্ধ", "স্বয়ংক্রিয় ডাউনলোড না এলে ডাউনলোড চাপুন। iPhone-এ Share থেকে Save to Files বেছে নিন। সংরক্ষণের অনুরোধ নিশ্চিত করুন।", "শেয়ার খোলা যায়নি। ডাউনলোড চাপুন বা Safari কিংবা Chrome-এ চেষ্টা করুন।"],
  kk: ["Файлды алдын ала қарау", "Жүктеу", "Бөлісу / Файлдарға сақтау", "Жабу", "Автоматты жүктеу басталмаса, Жүктеу түймесін басыңыз. iPhone-да Бөлісу мәзірінен Файлдарға сақтау тармағын таңдаңыз. Сақтау сұрауын растаңыз.", "Бөлісу мәзірі ашылмады. Жүктеу түймесін басыңыз немесе Safari, Chrome арқылы қайталаңыз."],
  jp: ["ファイルのプレビュー", "ダウンロード", "共有 / ファイルに保存", "閉じる", "自動ダウンロードが表示されない場合はダウンロードを押してください。iPhoneでは共有から「ファイルに保存」を選べます。保存の確認が出たら承認してください。", "共有を開けませんでした。ダウンロードを押すか、SafariまたはChromeで再試行してください。"],
  fr: ["Aperçu du fichier", "Télécharger", "Partager / Enregistrer dans Fichiers", "Fermer", "Si le téléchargement automatique ne démarre pas, appuyez sur Télécharger. Sur iPhone, choisissez Enregistrer dans Fichiers via Partager. Confirmez toute demande d’enregistrement.", "Impossible d’ouvrir le partage. Appuyez sur Télécharger ou réessayez dans Safari ou Chrome."],
  es: ["Vista previa del archivo", "Descargar", "Compartir / Guardar en Archivos", "Cerrar", "Si no empieza la descarga automática, pulsa Descargar. En iPhone, elige Guardar en Archivos desde Compartir. Confirma cualquier solicitud para guardar.", "No se pudo abrir Compartir. Pulsa Descargar o inténtalo en Safari o Chrome."],
  ar: ["معاينة الملف", "تنزيل", "مشاركة / حفظ في الملفات", "إغلاق", "إذا لم يبدأ التنزيل التلقائي، اضغط تنزيل. على iPhone، اختر حفظ في الملفات من المشاركة. أكّد أي طلب للحفظ.", "تعذر فتح المشاركة. اضغط تنزيل أو حاول في Safari أو Chrome."],
  hi: ["फ़ाइल पूर्वावलोकन", "डाउनलोड", "साझा करें / Files में सहेजें", "बंद करें", "अपने आप डाउनलोड न हो तो डाउनलोड दबाएँ। iPhone पर Share से Save to Files चुनें। सहेजने का अनुरोध आने पर पुष्टि करें।", "साझा करना नहीं खुल सका। डाउनलोड दबाएँ या Safari या Chrome में फिर कोशिश करें।"],
};
