import type { FeatureVisual } from "@/components/ResponsiveFeatureHero";

export const visualizationSpecs = {
  access: { image: "access", eyebrow: "SECURE ACCESS", title: "로그인 · 본인 확인", description: "이름 중심의 간단하고 안전한 현장 입장", metrics: [{ label: "오늘 인증", value: "286명" }, { label: "승인 대기", value: "4명" }, { label: "인증률", value: "98.6%" }], steps: [{ title: "정보 확인", description: "이름과 최소정보 확인" }, { title: "현장 연결", description: "배정 현장 자동 확인" }, { title: "입장 완료", description: "근로자 세션 발급" }] },
  dashboard: { image: "dashboard", eyebrow: "CONTROL CENTER", title: "관리자 통합 현황", description: "위험과 미처리 업무를 한 화면에서 확인", metrics: [{ label: "출력 인원", value: "286명" }, { label: "TBM 완료", value: "94%" }, { label: "조치 필요", value: "7건" }], steps: [{ title: "인원 현황", description: "출입·교육 상태 집계" }, { title: "위험 확인", description: "미조치 항목 우선 표시" }, { title: "보고 준비", description: "오늘 문서 자동 정리" }] },
  onboarding: { image: "onboarding", eyebrow: "QUICK ONBOARDING", title: "신규 · QR 근로자 등록", description: "최소 정보와 현장 코드로 빠르게 시작", metrics: [{ label: "신규 등록", value: "18명" }, { label: "확인 완료", value: "16명" }, { label: "평균 시간", value: "52초" }], steps: [{ title: "QR 접속", description: "별도 앱 없이 시작" }, { title: "정보 입력", description: "이름·생년월일·전화번호" }, { title: "현장 승인", description: "관리자 확인 후 입장" }] },
  nfcQr: { image: "nfc-qr", eyebrow: "TAP AND GO", title: "NFC · QR 출입", description: "태그 또는 스캔으로 출입과 참석 자동 기록", metrics: [{ label: "NFC 출입", value: "214명" }, { label: "QR 출입", value: "72명" }, { label: "오류", value: "2건" }], steps: [{ title: "카드 태그", description: "NFC 또는 QR 인식" }, { title: "신원 확인", description: "현장·근로자 자동 매칭" }, { title: "기록 저장", description: "출입·참석 동시 기록" }] },
  tbm: { image: "tbm", eyebrow: "MULTILINGUAL TBM", title: "다국어 TBM", description: "데이터센터 골조 현장의 위험요인을 같은 의미로 전달", metrics: [{ label: "참석", value: "268명" }, { label: "서명 완료", value: "251명" }, { label: "지원 언어", value: "20개" }], steps: [{ title: "위험 전파", description: "오늘 작업과 위험요인 안내" }, { title: "다국어 확인", description: "근로자 언어로 자동 전달" }, { title: "전자 서명", description: "개인 장비 상태와 참석 확인" }] },
  education: { image: "education", eyebrow: "SAFETY LEARNING", title: "안전교육 · 퀴즈", description: "교육 직후 이해도를 확인하고 자동 기록", metrics: [{ label: "교육 대상", value: "42명" }, { label: "수료", value: "38명" }, { label: "평균 점수", value: "91점" }], steps: [{ title: "교육 진행", description: "작업별 핵심 수칙 학습" }, { title: "퀴즈 확인", description: "간단 문항으로 이해도 확인" }, { title: "수료 처리", description: "결과와 서명 자동 저장" }] },
  documents: { image: "documents", eyebrow: "AUTO DOCUMENTS", title: "서명 · 확인서 자동화", description: "한 번의 서명으로 참석부와 확인서 자동 생성", metrics: [{ label: "오늘 서명", value: "251건" }, { label: "생성 문서", value: "14개" }, { label: "누락", value: "3건" }], steps: [{ title: "전자 서명", description: "휴대폰에서 간단 서명" }, { title: "문서 조합", description: "현장·교육·참석 정보 결합" }, { title: "자동 출력", description: "PDF·Excel·Word·HWP 생성" }] },
  diary: { image: "diary", eyebrow: "DAILY SAFETY LOG", title: "안전일지 자동화", description: "점검 기록을 일지와 보고서로 자동 정리", metrics: [{ label: "점검 완료", value: "24건" }, { label: "사진 기록", value: "68장" }, { label: "조치 중", value: "6건" }], steps: [{ title: "현장 점검", description: "사진과 체크리스트 기록" }, { title: "위험 조치", description: "담당자와 기한 지정" }, { title: "일지 생성", description: "오늘 기록 자동 문서화" }] },
  live: { image: "live", eyebrow: "LIVE FIELD", title: "실시간 현장 모니터링", description: "위험구역과 미확인 인원을 현장에서 즉시 확인", metrics: [{ label: "활성 구역", value: "12곳" }, { label: "현장 인원", value: "286명" }, { label: "알림", value: "4건" }], steps: [{ title: "구역 확인", description: "작업구역 상태 실시간 표시" }, { title: "위험 알림", description: "미확인·위험 행동 감지" }, { title: "현장 조치", description: "담당자 확인과 종료 기록" }] },
  translate: { image: "translate", eyebrow: "LIVE INTERPRETER", title: "다국어 통역 · 용어", description: "현장 전문용어까지 같은 의미로 전달", metrics: [{ label: "오늘 통역", value: "126건" }, { label: "지원 언어", value: "20개" }, { label: "용어집", value: "384개" }], steps: [{ title: "언어 선택", description: "근로자 선호 언어 확인" }, { title: "실시간 통역", description: "음성과 텍스트 동시 전달" }, { title: "용어 통일", description: "안전 전문용어 자동 적용" }] },
  esg: { image: "esg", eyebrow: "ESG REPORT", title: "ESG 안전 리포트", description: "안전활동을 자동 집계해 의사결정 자료로 제공", metrics: [{ label: "TBM 참여율", value: "94%" }, { label: "교육 수료율", value: "91%" }, { label: "조치 완료율", value: "87%" }], steps: [{ title: "데이터 집계", description: "출입·교육·TBM·조치 통합" }, { title: "성과 분석", description: "현장·기간별 지표 비교" }, { title: "리포트 출력", description: "PDF·Excel·Word·HWP 내보내기" }] },
} satisfies Record<string, FeatureVisual>;
