CREATE TABLE organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES organizations(id),
  name TEXT NOT NULL,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status IN ('ACTIVE', 'SUSPENDED', 'ARCHIVED'))
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  display_name TEXT NOT NULL,
  preferred_language TEXT NOT NULL DEFAULT 'ko',
  account_status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (account_status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED')),
  CHECK (email IS NOT NULL OR phone IS NOT NULL)
);

CREATE TABLE user_credentials (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL,
  password_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  disabled_at TIMESTAMPTZ
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  granted_by BIGINT REFERENCES users(id),
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  PRIMARY KEY (user_id, role, granted_at),
  CHECK (role IN ('ROOT', 'HQ_ADMIN', 'SITE_ADMIN', 'SAFETY_MANAGER', 'WORKER', 'VIEWER'))
);

CREATE TABLE site_memberships (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, site_id, role),
  CHECK (role IN ('SITE_ADMIN', 'SAFETY_MANAGER', 'WORKER', 'VIEWER')),
  CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED'))
);

CREATE TABLE admin_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT,
  phone TEXT,
  target_role TEXT NOT NULL,
  target_site_id BIGINT REFERENCES sites(id),
  token_hash TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'PENDING',
  invited_by BIGINT NOT NULL REFERENCES users(id),
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_by BIGINT REFERENCES users(id),
  accepted_at TIMESTAMPTZ,
  decided_by BIGINT REFERENCES users(id),
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (target_role IN ('HQ_ADMIN', 'SITE_ADMIN', 'SAFETY_MANAGER', 'VIEWER')),
  CHECK (status IN ('PENDING', 'ACCEPTED', 'APPROVED', 'REJECTED', 'REVOKED', 'EXPIRED')),
  CHECK (email IS NOT NULL OR phone IS NOT NULL)
);

CREATE INDEX idx_sites_org ON sites (organization_id);
CREATE INDEX idx_user_roles_active_user ON user_roles (user_id, role) WHERE revoked_at IS NULL;
CREATE INDEX idx_site_memberships_site_user ON site_memberships (site_id, user_id);
CREATE INDEX idx_admin_invitations_status_expiry ON admin_invitations (status, expires_at);
