CREATE TABLE file_objects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT NOT NULL REFERENCES sites(id),
  owner_user_id BIGINT REFERENCES users(id),
  object_key TEXT NOT NULL UNIQUE,
  sha256 TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  byte_size BIGINT NOT NULL,
  purpose TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING_UPLOAD',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  verified_at TIMESTAMPTZ,
  CHECK (byte_size > 0),
  CHECK (status IN ('PENDING_UPLOAD', 'READY', 'QUARANTINED', 'DELETED'))
);

CREATE INDEX idx_file_objects_site_owner ON file_objects (site_id, owner_user_id);
CREATE INDEX idx_file_objects_site_purpose ON file_objects (site_id, purpose, created_at DESC);
