CREATE TABLE tbm_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT NOT NULL REFERENCES sites(id),
  created_by BIGINT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  source_text TEXT NOT NULL,
  normalized_text TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE tbm_acknowledgements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tbm_notice_id BIGINT NOT NULL REFERENCES tbm_notices(id),
  worker_id BIGINT NOT NULL REFERENCES users(id),
  site_id BIGINT NOT NULL REFERENCES sites(id),
  acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  signature_file_id BIGINT REFERENCES file_objects(id),
  UNIQUE (tbm_notice_id, worker_id)
);

CREATE INDEX idx_tbm_notices_site_published ON tbm_notices (site_id, published_at DESC);
CREATE INDEX idx_tbm_ack_site_notice ON tbm_acknowledgements (site_id, tbm_notice_id);
