CREATE TABLE chat_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT NOT NULL REFERENCES sites(id),
  worker_id BIGINT NOT NULL REFERENCES users(id),
  admin_user_id BIGINT REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status IN ('OPEN', 'CLOSED', 'ARCHIVED'))
);

CREATE TABLE chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES chat_threads(id),
  site_id BIGINT NOT NULL REFERENCES sites(id),
  sender_user_id BIGINT NOT NULL REFERENCES users(id),
  source_language TEXT NOT NULL,
  target_language TEXT NOT NULL,
  source_text TEXT NOT NULL,
  translated_text TEXT,
  audio_file_id BIGINT REFERENCES file_objects(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE chat_message_reads (
  message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
  reader_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, reader_user_id)
);

CREATE INDEX idx_chat_threads_site_worker ON chat_threads (site_id, worker_id);
CREATE INDEX idx_chat_messages_thread_time ON chat_messages (thread_id, created_at);
CREATE INDEX idx_chat_messages_site_time ON chat_messages (site_id, created_at DESC);
