CREATE TABLE ai_usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id BIGINT REFERENCES users(id),
  site_id BIGINT REFERENCES sites(id),
  feature TEXT NOT NULL,
  vendor TEXT NOT NULL,
  model TEXT,
  input_size BIGINT NOT NULL DEFAULT 0,
  output_size BIGINT NOT NULL DEFAULT 0,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  estimated_cost NUMERIC(12, 6) NOT NULL DEFAULT 0
);

CREATE TABLE ai_quota_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type TEXT NOT NULL,
  scope_id BIGINT,
  feature TEXT NOT NULL,
  limit_count BIGINT NOT NULL,
  limit_cost NUMERIC(12, 6),
  window_seconds BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (scope_type IN ('GLOBAL', 'SITE', 'USER')),
  CHECK (limit_count > 0),
  CHECK (window_seconds > 0)
);

CREATE INDEX idx_ai_usage_site_time ON ai_usage_logs (site_id, occurred_at DESC);
CREATE INDEX idx_ai_usage_user_time ON ai_usage_logs (user_id, occurred_at DESC);
CREATE INDEX idx_ai_quota_policies_scope_feature ON ai_quota_policies (scope_type, scope_id, feature);
