CREATE TABLE worker_daily_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  work_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  checked_in_at TIMESTAMPTZ,
  checked_out_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  entry_method TEXT NOT NULL DEFAULT 'QR',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (worker_id, site_id, work_date),
  CHECK (status IN ('ACTIVE', 'CHECKED_OUT')),
  CHECK (entry_method IN ('QR', 'NFC', 'MANUAL', 'SYSTEM'))
);

CREATE INDEX idx_worker_daily_access_site_date
  ON worker_daily_access (site_id, work_date, status);

CREATE INDEX idx_worker_daily_access_worker_date
  ON worker_daily_access (worker_id, work_date DESC);
