ALTER TABLE sites
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS geofence_radius_m INTEGER NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS site_code TEXT;

CREATE TABLE worker_profiles (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  worker_code TEXT NOT NULL UNIQUE,
  nationality TEXT NOT NULL DEFAULT 'KR',
  phone TEXT,
  trade TEXT NOT NULL DEFAULT 'general',
  consent_signed_at TIMESTAMPTZ,
  consent_doc_url TEXT,
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  nationality_confirmed_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (nationality ~ '^[A-Z]{2}$'),
  CHECK (trade ~ '^[a-z0-9_-]{1,32}$')
);

CREATE INDEX idx_worker_profiles_active ON worker_profiles (is_active) WHERE is_active = true;
CREATE INDEX idx_worker_profiles_trade ON worker_profiles (trade);

CREATE TABLE worker_qr_token_nonces (
  nonce TEXT PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_worker_qr_token_nonces_expires ON worker_qr_token_nonces (expires_at);
CREATE INDEX idx_worker_qr_token_nonces_worker ON worker_qr_token_nonces (worker_id);

CREATE TABLE worker_stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  sig_version INTEGER NOT NULL,
  issued_epoch BIGINT NOT NULL,
  identity_hint TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  issued_by BIGINT REFERENCES users(id),
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  revoked_by BIGINT REFERENCES users(id),
  revoke_reason TEXT,
  UNIQUE (worker_id, sig_version, issued_epoch)
);

CREATE UNIQUE INDEX uniq_worker_stickers_active
  ON worker_stickers (worker_id)
  WHERE is_active = true;

CREATE TABLE worker_card_lifecycle_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  sticker_id BIGINT REFERENCES worker_stickers(id) ON DELETE SET NULL,
  site_id BIGINT REFERENCES sites(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  actor_id BIGINT REFERENCES users(id),
  tag_uid TEXT,
  sig_version INTEGER,
  issued_epoch BIGINT,
  ndef_bytes INTEGER,
  reason TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (event_type IN ('issued', 'written', 'erased', 'revoked', 'reissued'))
);

CREATE INDEX idx_worker_card_events_worker_created
  ON worker_card_lifecycle_events (worker_id, created_at DESC);

CREATE TABLE site_access_controls (
  site_id BIGINT PRIMARY KEY REFERENCES sites(id) ON DELETE CASCADE,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  reason TEXT,
  updated_by BIGINT REFERENCES users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE site_daily_challenges (
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  work_date DATE NOT NULL,
  challenge_code TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  expires_at TIMESTAMPTZ NOT NULL,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (site_id, work_date)
);

CREATE INDEX idx_site_daily_challenges_active
  ON site_daily_challenges (site_id, work_date, is_active);
