CREATE TABLE tbm_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  tbm_notice_id TEXT,
  title TEXT,
  status TEXT NOT NULL DEFAULT 'running',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ,
  started_by BIGINT REFERENCES users(id),
  ended_by BIGINT REFERENCES users(id),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  CHECK (status IN ('open', 'running', 'closed'))
);

CREATE INDEX idx_tbm_sessions_site_started
  ON tbm_sessions (site_id, started_at DESC);

CREATE TABLE tbm_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES tbm_sessions(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sticker_id BIGINT REFERENCES worker_stickers(id) ON DELETE SET NULL,
  tapped_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  tapped_by BIGINT REFERENCES users(id),
  lang_used TEXT,
  is_certified BOOLEAN NOT NULL DEFAULT false,
  certified_at TIMESTAMPTZ,
  UNIQUE (session_id, worker_id)
);

CREATE INDEX idx_tbm_attendance_session
  ON tbm_attendance (session_id, tapped_at);

CREATE TABLE tbm_notification_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tbm_session_id BIGINT NOT NULL REFERENCES tbm_sessions(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  attempt_number INTEGER NOT NULL DEFAULT 1,
  next_retry_at TIMESTAMPTZ,
  channel TEXT NOT NULL DEFAULT 'push',
  status TEXT NOT NULL DEFAULT 'sent',
  sent_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tbm_notification_log_session
  ON tbm_notification_log (tbm_session_id, sent_at DESC);
