CREATE TABLE construction_glossary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slang TEXT NOT NULL UNIQUE,
  standard TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '기타',
  origin_lang TEXT DEFAULT 'ko',
  origin_word TEXT,
  note TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE site_term_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  glossary_id BIGINT NOT NULL REFERENCES construction_glossary(id) ON DELETE CASCADE,
  pivot_en TEXT NOT NULL,
  lang_code TEXT NOT NULL,
  local_slang TEXT NOT NULL,
  local_phonetic TEXT,
  colonial_origin TEXT,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION update_glossary_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_glossary_updated_at
  BEFORE UPDATE ON construction_glossary
  FOR EACH ROW EXECUTE FUNCTION update_glossary_updated_at();

INSERT INTO construction_glossary(slang, standard, category, origin_lang, origin_word, note) VALUES
('함바', '현장 구내식당', '시설', 'ja', '飯場(Hanba)', null),
('공구리', '콘크리트', '자재', 'ja', 'コンクリート', '타설 작업 통칭'),
('빠루', '쇠지렛대(노루발못뽑이)', '도구', 'ja', 'バール(Baru)', null),
('빠이프', '파이프', '자재', 'ja', 'パイプ', null),
('스라브', '슬래브', '자재', 'ja', 'スラブ', null),
('슬라브', '슬래브', '자재', 'ja', 'スラブ', null),
('몰탈', '모르타르', '자재', 'ja', 'モルタル', null),
('빠대', '퍼티(마감재)', '자재', 'ja', 'パテ', null),
('레미콘', '레디믹스 콘크리트', '자재', 'en', 'Ready-Mixed Concrete', null),
('갱폼', '대형 거푸집', '자재', 'en', 'Gang Form', null),
('비계', '가설발판(작업용 비계)', '시설', 'ja', '飛階', null),
('족장', '작업용 비계', '시설', 'ko', null, null),
('먹줄', '먹선(기준선 표시줄)', '도구', 'ko', null, null),
('가다와꾸', '거푸집', '자재', 'ja', '型枠(Kata-waku)', null),
('가이당', '계단', '시설', 'ja', '階段(Kaidan)', null),
('겐바', '현장', '기타', 'ja', '現場(Genba)', null),
('나라시', '고르기, 평탄화', '작업', 'ja', '均し(Narashi)', null),
('다루끼', '서까래, 각목', '자재', 'ja', '垂木(Taruki)', null),
('덴조', '천장', '시설', 'ja', '天井(Tenjo)', null),
('도비', '비계공(중량물 설치공)', '인원', 'ja', '鳶(Tobi)', null),
('루베', '입방미터 (m³)', '단위', 'ja', '立米(Ryube)', null),
('헤베', '평방미터 (m²)', '단위', 'ja', '平米(Heibe)', null),
('반생', '결속선(굵은 철사)', '자재', 'ja', '番線(Bansen)', null),
('바라시', '해체, 뜯기', '작업', 'ja', '晴らし(Barashi)', null),
('아시바', '비계(작업 발판)', '시설', 'ja', '足場(Ashiba)', null),
('야리끼리', '도급·할당제', '작업', 'ja', '遣り切り(Yarikiri)', '할당량 채우면 퇴근'),
('우마', '말비계(발판용 받침대)', '도구', 'ja', '馬(Uma)', null),
('하리', '보 (Beam)', '구조', 'ja', '梁(Hari)', null),
('하시라', '기둥 (Column)', '구조', 'ja', '柱(Hashira)', null),
('하스리', '쪼아내기(콘크리트 표면 정리)', '작업', 'ja', '斫り(Hatsuri)', null),
('단도리', '작업 준비 및 점검', '작업', 'ja', '段取り(Dandori)', null),
('타설', '콘크리트 타설(붓기)', '작업', 'ja', '打設(Dasetsu)', null),
('양생', '콘크리트 양생(강도 확보 대기)', '작업', 'ja', '養生(Yousei)', null),
('탈형', '거푸집 해체', '작업', 'ja', '脱型(Dakkei)', null),
('배근', '철근 배치', '작업', 'ja', '配筋(Haikin)', null),
('시마이', '작업 종료, 마감', '작업', 'ja', '仕舞い(Shimai)', null),
('나가리', '무산, 허사', '기타', 'ja', '流れ(Nagare)', null),
('오함마', '대형 망치', '도구', 'ja', '大ハンマー(O-Hamma)', null),
('노기스', '버니어 캘리퍼스', '도구', 'ja', 'ノギス(Nogisu)', null),
('야스리', '줄(연마 도구)', '도구', 'ja', '鑢(Yasuri)', null),
('임팩', '임팩트 렌치', '도구', 'en', 'Impact Wrench', null),
('샤클', '섀클(연결 고리)', '도구', 'en', 'Shackle', null),
('바께쓰', '양동이', '도구', 'ja', 'バケツ(Baketsu)', null),
('노가다', '현장 인부', '인원', 'ja', '土方(Dokata)', '사용 자제'),
('오야지', '현장 반장/팀장', '인원', 'ja', '親父(Oyaji)', null),
('데모도', '보조공, 조수', '인원', 'ja', '手元(Temoto)', null),
('아차사고', '경미한 안전사고', '안전', 'ko', null, null),
('하이바', '안전모(Fiber 헬멧)', '안전', 'ja', 'ファイバー(Faiba)', null),
('기스', '흠집, 스크래치', '상태', 'ja', '傷(Kizu)', null),
('빠꾸', '불량, 반품', '상태', 'ja', 'バック(Back)', null),
('만땅', '가득 채움', '기타', 'ja', '満タン(Mantan)', null),
('입빠이', '가득, 한껏', '기타', 'ja', '一杯(Ippai)', null),
('유도리', '융통성, 여유(공차)', '기타', 'ja', 'ゆとり(Yutori)', null)
ON CONFLICT (slang) DO UPDATE
SET standard = EXCLUDED.standard,
    category = EXCLUDED.category,
    origin_lang = EXCLUDED.origin_lang,
    origin_word = EXCLUDED.origin_word,
    note = EXCLUDED.note,
    updated_at = now();

INSERT INTO site_term_translations(glossary_id, pivot_en, lang_code, local_slang, local_phonetic, colonial_origin, note)
SELECT g.id, '결속선 (Binding Wire)', 'vi', 'Kẽm buộc', '껨 북', '佛(프랑스어)', null FROM construction_glossary g WHERE g.slang = '반생'
UNION ALL
SELECT g.id, '결속선 (Binding Wire)', 'th', 'Luat', '루앗', null, 'Luat Pook Lek의 단축형' FROM construction_glossary g WHERE g.slang = '반생'
UNION ALL
SELECT g.id, '결속선 (Binding Wire)', 'ph', 'Alambre', '알람브레', '西(스페인어)', null FROM construction_glossary g WHERE g.slang = '반생'
UNION ALL
SELECT g.id, '대형 망치 (Sledgehammer)', 'vi', 'Búa tạ', '부아 따', null, '망치+무거운' FROM construction_glossary g WHERE g.slang = '오함마'
UNION ALL
SELECT g.id, '대형 망치 (Sledgehammer)', 'th', 'Khon Pond', '콘 뽄', '英(영어)', 'Pound Hammer의 태국식 변형' FROM construction_glossary g WHERE g.slang = '오함마'
UNION ALL
SELECT g.id, '콘크리트 (Concrete)', 'vi', 'Bê tông', '베 똥', '佛(프랑스어)', 'Béton에서 유래' FROM construction_glossary g WHERE g.slang = '공구리'
UNION ALL
SELECT g.id, '콘크리트 (Concrete)', 'th', 'Poon', '뿐', null, '시멘트/콘크리트 통칭' FROM construction_glossary g WHERE g.slang = '공구리'
UNION ALL
SELECT g.id, '안전모 (Safety Helmet)', 'vi', 'Mũ bảo hộ', '무 바오 호', null, '보호 모자' FROM construction_glossary g WHERE g.slang = '하이바'
UNION ALL
SELECT g.id, '안전모 (Safety Helmet)', 'ph', 'Hard Hat', '하드 햇', '英(영어)', '미국 영향' FROM construction_glossary g WHERE g.slang = '하이바';

CREATE INDEX idx_glossary_slang ON construction_glossary(slang);
CREATE INDEX idx_glossary_category ON construction_glossary(category);
CREATE INDEX idx_glossary_active ON construction_glossary(is_active) WHERE is_active = true;
CREATE INDEX idx_translations_glossary ON site_term_translations(glossary_id);
CREATE INDEX idx_translations_lang ON site_term_translations(lang_code);
