CREATE TABLE claim13_hash_chain_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  previous_hash TEXT,
  event_hash TEXT NOT NULL,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_claim13_hash_chain_site_id
  ON claim13_hash_chain_events(site_id, id);

CREATE INDEX idx_claim13_hash_chain_entity
  ON claim13_hash_chain_events(entity_type, entity_id, id);

CREATE TABLE claim13_pledges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tbm_session_id TEXT,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  pledge_content TEXT NOT NULL,
  pledge_content_hash TEXT NOT NULL,
  nfc_uid TEXT,
  signature_file_id BIGINT REFERENCES file_objects(id) ON DELETE SET NULL,
  signature_sha256 TEXT,
  client_ip TEXT,
  approved_at TIMESTAMPTZ,
  hash_chain_event_id BIGINT REFERENCES claim13_hash_chain_events(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_claim13_pledges_session
  ON claim13_pledges(tbm_session_id);

CREATE INDEX idx_claim13_pledges_worker
  ON claim13_pledges(worker_id, created_at DESC);

CREATE INDEX idx_claim13_pledges_site_created
  ON claim13_pledges(site_id, created_at DESC);
