CREATE TABLE tbm_quiz_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tbm_session_id BIGINT REFERENCES tbm_sessions(id) ON DELETE SET NULL,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  source TEXT NOT NULL DEFAULT 'fallback',
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status IN ('draft', 'sent', 'closed')),
  CHECK (source IN ('tbm', 'fallback'))
);

CREATE INDEX idx_tbm_quiz_sessions_site_created
  ON tbm_quiz_sessions(site_id, created_at DESC);

CREATE INDEX idx_tbm_quiz_sessions_tbm
  ON tbm_quiz_sessions(tbm_session_id, created_at DESC);

CREATE TABLE tbm_quiz_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_session_id BIGINT NOT NULL REFERENCES tbm_quiz_sessions(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lang TEXT NOT NULL DEFAULT 'ko',
  questions_translated JSONB NOT NULL DEFAULT '[]'::jsonb,
  answer_index_correct JSONB NOT NULL DEFAULT '[]'::jsonb,
  answers_submitted JSONB,
  score_pct INTEGER,
  status TEXT NOT NULL DEFAULT 'sent',
  answered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status IN ('sent', 'answered')),
  CHECK (score_pct IS NULL OR (score_pct >= 0 AND score_pct <= 100)),
  UNIQUE (quiz_session_id, worker_id)
);

CREATE INDEX idx_tbm_quiz_responses_session_status
  ON tbm_quiz_responses(quiz_session_id, status);

CREATE INDEX idx_tbm_quiz_responses_worker_created
  ON tbm_quiz_responses(worker_id, created_at DESC);

CREATE TABLE safety_equipment_grants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  quiz_session_id BIGINT REFERENCES tbm_quiz_sessions(id) ON DELETE SET NULL,
  score_pct INTEGER,
  equipment_type TEXT NOT NULL,
  granted_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  note TEXT,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (score_pct IS NULL OR (score_pct >= 0 AND score_pct <= 100))
);

CREATE UNIQUE INDEX uniq_safety_equipment_grants_quiz_equipment
  ON safety_equipment_grants(worker_id, equipment_type, quiz_session_id)
  WHERE quiz_session_id IS NOT NULL;

CREATE UNIQUE INDEX uniq_safety_equipment_grants_manual_equipment
  ON safety_equipment_grants(worker_id, equipment_type)
  WHERE quiz_session_id IS NULL;

CREATE INDEX idx_safety_equipment_grants_site_created
  ON safety_equipment_grants(site_id, created_at DESC);

CREATE TABLE stop_work_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  worker_name TEXT NOT NULL,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  lang TEXT NOT NULL DEFAULT 'ko',
  resolved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolved_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_stop_work_alerts_site_created
  ON stop_work_alerts(site_id, created_at DESC);

CREATE INDEX idx_stop_work_alerts_unresolved
  ON stop_work_alerts(site_id, created_at DESC)
  WHERE resolved = false;

CREATE TABLE claim17_stop_work_interventions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES stop_work_alerts(id) ON DELETE CASCADE,
  worker_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  hazard_category TEXT NOT NULL DEFAULT 'unspecified',
  severity TEXT NOT NULL DEFAULT 'high',
  preferred_lang TEXT NOT NULL DEFAULT 'ko',
  gps JSONB,
  photo_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'requested',
  escalation_due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CHECK (status IN ('requested', 'acknowledged', 'resolved', 'rejected'))
);

CREATE INDEX idx_claim17_stop_work_site_created
  ON claim17_stop_work_interventions(site_id, created_at DESC);

CREATE TABLE stop_work_alert_routing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES stop_work_alerts(id) ON DELETE CASCADE,
  admin_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  admin_role TEXT NOT NULL,
  is_priority BOOLEAN NOT NULL DEFAULT false,
  escalation_due_at TIMESTAMPTZ,
  routed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (alert_id, admin_id)
);

CREATE INDEX idx_stop_work_alert_routing_admin
  ON stop_work_alert_routing(admin_id, routed_at DESC);
