CREATE TABLE live_translation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  site_id BIGINT REFERENCES sites(id) ON DELETE CASCADE,
  text_ko TEXT NOT NULL,
  translations JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_live_translation_events_site_id
  ON live_translation_events(site_id, id DESC);

CREATE INDEX idx_live_translation_events_session
  ON live_translation_events(session_id, id DESC);

CREATE TABLE live_worker_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  admin_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source_lang TEXT NOT NULL,
  source_text TEXT NOT NULL,
  translated_text TEXT NOT NULL,
  speaker_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_live_worker_responses_admin
  ON live_worker_responses(admin_id, id DESC);

CREATE INDEX idx_live_worker_responses_site
  ON live_worker_responses(site_id, id DESC);
