ALTER TABLE users
  ADD COLUMN deletion_requested_at TIMESTAMPTZ,
  ADD COLUMN anonymized_at TIMESTAMPTZ;

ALTER TABLE file_objects
  ADD COLUMN retention_until TIMESTAMPTZ,
  ADD COLUMN legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN deleted_at TIMESTAMPTZ;

CREATE TABLE account_deletion_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'REQUESTED',
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  reason TEXT,
  requester_ip INET,
  CHECK (status IN ('REQUESTED', 'COMPLETED', 'REJECTED'))
);

CREATE TABLE data_retention_policies (
  data_type TEXT PRIMARY KEY,
  retention_days INTEGER NOT NULL,
  description TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (retention_days >= 0)
);

INSERT INTO data_retention_policies(data_type, retention_days, description) VALUES
  ('ACCOUNT_PROFILE', 0, '기술 기본값: 탈퇴 시 즉시 가명처리'),
  ('SECURITY_AUDIT', 1825, '기술 기본값: 보안 및 권한 감사 기록'),
  ('SAFETY_RECORD', 1825, '기술 기본값: TBM, 서명, 작업중지 등 안전 기록'),
  ('CHAT_MESSAGE', 365, '기술 기본값: 현장 채팅 기록'),
  ('TEMPORARY_UPLOAD', 30, '기술 기본값: 연결되지 않은 임시 업로드')
ON CONFLICT (data_type) DO NOTHING;

CREATE INDEX idx_account_deletion_requests_user ON account_deletion_requests(user_id, requested_at DESC);
CREATE INDEX idx_file_objects_retention_due ON file_objects(retention_until)
  WHERE status = 'READY' AND legal_hold = FALSE;
