CREATE TABLE worker_upgrade_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
 site_id BIGINT NOT NULL REFERENCES sites(id),
 display_name TEXT NOT NULL,
 phone TEXT NOT NULL,
 iris_id TEXT NOT NULL CHECK (iris_id ~ '^[0-9]{1,64}$'),
 consent_version TEXT NOT NULL,
 consented_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
 revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
 requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 decided_by BIGINT REFERENCES users(id),
 decided_at TIMESTAMPTZ,
 decision_reason TEXT,
 verification_method TEXT,
 CHECK (status <> 'APPROVED' OR (decided_by IS NOT NULL AND verification_method = 'MANUAL_CONTRACT_CHECK'))
);
CREATE UNIQUE INDEX worker_upgrade_approved_iris ON worker_upgrade_requests(iris_id) WHERE status='APPROVED';
CREATE INDEX worker_upgrade_site_pending ON worker_upgrade_requests(site_id,status);
